spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: efemfirebase@gmail.com
    password: 135579++
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console  # Konsol adresini belirtmek iyi olur

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

scheduler:
  reminder:
    cron: "0 0 13 ? * FRI"  # Cuma günü saat 13:00
